<a href="https://colab.research.google.com/github/Anikrai11/titanic/blob/main/assainment_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn .linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

In [27]:
df=pd.read_csv("/content/12 assainment.zip")

/tmp/ipykernel_32778/3376016522.py:1: DtypeWarning: Columns (22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/12 assainment.zip")

In [28]:
df.head(1)

,text,label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.iloc[:,:2]
df[["text","label"]]

                                                   text label
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE
2     U.S. Secretary of State John F. Kerry said Mon...  REAL
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE
4     It's primary day in New York and front-runners...  REAL
...                                                 ...   ...
7790  The State Department told the Republican Natio...  REAL
7791  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE
7792   Anti-Trump Protesters Are Tools of the Oligar...  FAKE
7793  ADDIS ABABA, Ethiopia —President Obama convene...  REAL
7794  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL

[7795 rows x 2 columns]

In [30]:
df=df[df["label"].isin(["FAKE","REAL"])].dropna(subset=["text"])

In [31]:
df.shape

(6315, 139)

In [32]:
df["label"].value_counts()

label
REAL    3161
FAKE    3154
Name: count, dtype: int64

In [33]:
x_train,x_test,y_train,y_test=train_test_split(df["text"],df["label"],test_size=0.2,random_state=42)

In [34]:
tfidf=TfidfVectorizer(stop_words="english",max_df=0.7)
tfidf_train=tfidf.fit_transform(x_train)
tfidf_test=tfidf.transform(x_test)

In [35]:
tfidf_train.shape

(5052, 59875)

#model_training

In [36]:
model=PassiveAggressiveClassifier(max_iter=50)
model.fit(tfidf_train,y_train)

PassiveAggressiveClassifier(max_iter=50)

In [37]:
y_pred=model.predict(tfidf_test)

In [38]:
y_pred

array(['FAKE', 'REAL', 'REAL', ..., 'FAKE', 'REAL', 'FAKE'], dtype='<U4')

In [39]:
accuracy=accuracy_score(y_test,y_pred)

In [40]:
accuracy

0.9469517022961204

In [41]:
cm=confusion_matrix(y_test,y_pred,labels=["FAKE","REAL"])
cm

array([[585,  31],
       [ 36, 611]])

In [42]:
new_news=["Scientists at NASA confirmed a new exoplanet discovery yesterday."]
v=tfidf.transform(new_news)
model.predict(v)

array(['FAKE'], dtype='<U4')

#next_steps

In [43]:
mdel=LogisticRegression(max_iter=1000)
mdel.fit(tfidf_train,y_train)

LogisticRegression(max_iter=1000)

In [25]:
tfidf=TfidfVectorizer(stop_words="english",max_df=0.7)
tfidf_train=tfidf.fit_transform(x_train)
tfidf_test=tfidf.transform(x_test)

In [44]:
print(type(mdel))

<class 'sklearn.linear_model._logistic.LogisticRegression'>

In [45]:
y_pred=mdel.predict(tfidf_test)

In [46]:
accuracy=accuracy_score(y_test,y_pred)

In [47]:
accuracy

0.9263657957244655

In [48]:
Cm=confusion_matrix(y_test,y_pred,labels=["FAKE","REAL"])

In [49]:
Cm

array([[587,  29],
       [ 64, 583]])